inveniosoftware-contrib/ng2-json-editor

src/abstract-list-field/abstract-list-field.component.ts
src/object-field/object-field.component.ts
src/primitive-field/primitive-field.component.ts

refactor event function names

---

src/shared/services/empty-value.service.ts

change new number field default value

---

src/autocomplete-input/autocomplete-input.component.spec.ts
src/shared/pipes/errors-to-message.pipe.spec.ts

* Adds test for errors-to-message pipe.
* Adds stub test for autocomplete-input component. (#8)

add tests for components and pipes

---

package.json
src/primitive-list-field/primitive-list-field.component.ts
src/shared/services/record-fixer.service.ts

Tremendous random fixes

---

src/add-field-dropdown/add-field-dropdown.component.scss
src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.scss
src/json-editor.component.html
src/json-editor.component.scss
src/object-field/object-field.component.scss
src/primitive-list-field/primitive-list-field.component.html
src/table-list-field/table-list-field.component.html
src/table-list-field/table-list-field.component.scss
src/tree-menu/tree-menu-item.component.scss
src/tree-menu/tree-menu.component.html
src/tree-menu/tree-menu.component.scss

layout and css improvements

---

README.md
example/app/app.component.ts
example/app/app.config.ts
example/app/app.module.ts
src/json-editor.component.ts
src/shared/services/index.ts
src/shared/services/schema-fixer.service.ts
src/typings.d.ts

enrich schema with configuration

---

src/abstract-list-field/abstract-list-field.component.ts
src/add-new-element-button/add-new-element-button.component.html
src/add-new-element-button/add-new-element-button.component.scss
src/add-new-element-button/add-new-element-button.component.ts
src/add-new-element-button/index.ts
src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.ts
src/json-editor.component.html
src/json-editor.component.scss
src/json-editor.module.ts
src/object-field/object-field.component.html
src/primitive-list-field/primitive-list-field.component.html
src/table-list-field/table-list-field.component.html
src/table-list-field/table-list-field.component.ts

- Creates add-new-element-button component that enables to move
add-new-element button and its logic to the parent so that it will
appear in the space under the key/title of property.

create add-new-element-button component

---

package.json
src/abstract-list-field/abstract-list-field.component.ts
src/add-new-element-button/add-new-element-button.component.ts
src/any-type-field/any-type-field.component.ts
src/autocomplete-input/autocomplete-input.component.ts
src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.ts
src/json-editor.component.html
src/json-editor.component.ts
src/object-field/object-field.component.html
src/object-field/object-field.component.ts
src/primitive-field/primitive-field.component.ts
src/primitive-list-field/primitive-list-field.component.html
src/primitive-list-field/primitive-list-field.component.ts
src/searchable-dropdown/searchable-dropdown.component.spec.ts
src/searchable-dropdown/searchable-dropdown.component.ts
src/shared/services/empty-value.service.spec.ts
src/shared/services/empty-value.service.ts
src/table-list-field/table-list-field.component.html
src/table-list-field/table-list-field.component.ts
src/tree-menu/tree-menu-item.component.html
src/tree-menu/tree-menu-item.component.ts
src/tree-menu/tree-menu.component.html
src/tree-menu/tree-menu.component.ts

* Uses immutablejs for value inputs in components
that are likely to change
* Fixes #55
* Fixes #10
* Fixes #60
* Fixes broken tests

move to immutablejs for performance

---

src/object-field/object-field.component.html

fix add new element bug for lists in objects

---

README.md
src/primitive-field/primitive-field.component.spec.ts
src/searchable-dropdown/searchable-dropdown.component.html
src/searchable-dropdown/searchable-dropdown.component.spec.ts
src/searchable-dropdown/searchable-dropdown.component.ts
src/shared/pipes/filter-by-expression.pipe.spec.ts
src/shared/pipes/filter-by-expression.pipe.ts
src/shared/pipes/index.ts

* Changes from prefix search to ignored case expression search which tries to
match given input in anywhere of possible items.
* Fixes #43
* Fixes #44

Searchable dropdown fix

---

src/add-field-dropdown/add-field-dropdown.component.html
src/add-field-dropdown/add-field-dropdown.component.scss
src/add-field-dropdown/add-field-dropdown.component.spec.ts
src/add-field-dropdown/add-field-dropdown.component.ts

add filtering to add-field-dropdown

---

README.md
src/editor-previewer/editor-previewer.component.html
src/editor-previewer/editor-previewer.component.ts
src/html-view/html-view.component.html
src/html-view/html-view.component.scss
src/html-view/html-view.component.ts
src/html-view/index.ts
src/json-editor.component.ts
src/json-editor.module.ts
src/shared/pipes/index.ts
src/shared/pipes/sanitize-url.pipe.ts
src/typings.d.ts

* Adds html-view component that loads remote html.
* Adds html support to previewer. (Fixes #39)
displays http://arxiv.org/licenses/nonexclusive-distrib/1.0/ as an example.

add html-view component and html preview support

---

src/add-new-element-button/add-new-element-button.component.html
src/add-new-element-button/add-new-element-button.component.scss
src/add-new-element-button/add-new-element-button.component.ts
src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.ts
src/json-editor.component.html
src/json-editor.component.scss
src/json-editor.module.ts
src/object-field/object-field.component.html
src/title-dropdown/index.ts
src/title-dropdown/title-dropdown.component.html
src/title-dropdown/title-dropdown.component.scss
src/title-dropdown/title-dropdown.component.ts

* Adds title-dropdown that is used to hide some action buttons
such as add-new-element and delete.
* Removes extra space from button-holder column.

add title-dropdown (fixes #92)

---

src/searchable-dropdown/searchable-dropdown.component.scss

fix searchable dropdown alignment

---

src/abstract-field/abstract-field.component.ts
src/abstract-list-field/abstract-list-field.component.ts
src/abstract-tracker/abstract-tracker.component.ts
src/add-field-dropdown/add-field-dropdown.component.html
src/add-field-dropdown/add-field-dropdown.component.scss
src/add-field-dropdown/add-field-dropdown.component.spec.ts
src/add-field-dropdown/add-field-dropdown.component.ts
src/complex-list-field/complex-list-field.component.html
src/json-editor.component.html
src/json-editor.component.scss
src/json-editor.component.ts
src/object-field/object-field.component.html
src/primitive-field/primitive-field.component.html
src/primitive-list-field/primitive-list-field.component.html
src/table-list-field/table-list-field.component.html
src/tree-menu/tree-menu.component.scss

* Fixes #101
* Fixes #42
* Refactors css regarding to margin and padding rules.
I did some extra styling, to make it more natural and understandable (at least to me 😄 ) but I am not sure if they are OK
@jmartinm

add top-level add and delete field

---

src/object-field/object-field.component.html

* Removes unnecessary ngIf.
* Adds comments to specify parts of template.

refactor object-field template

---

src/json-editor.component.ts
src/shared/pipes/filter-and-sort-by-schema.pipe.ts
src/shared/services/component-type.service.spec.ts
src/shared/services/component-type.service.ts
src/shared/services/json-util.service.ts
src/shared/services/record-fixer.service.ts
src/shared/services/schema-fixer.service.ts

I can squash commits if request when review is done.

Improve error/warning handling and messages

---

package.json
src/add-field-dropdown/add-field-dropdown.component.spec.ts
src/autocomplete-input/autocomplete-input.component.spec.ts
src/json-editor.component.ts
src/json-editor.module.ts
src/primitive-field/primitive-field.component.spec.ts
src/searchable-dropdown/searchable-dropdown.component.spec.ts

Add sanity check for undefined config

---

README.md
example/app/app.config.ts
src/table-list-field/table-list-field.component.html

field-width: Configure column width for every field

---

example/app/app.config.ts
src/any-type-field/any-type-field.component.html
src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.scss
src/json-editor.component.html
src/json-editor.component.scss
src/object-field/object-field.component.html
src/shared/services/component-type.service.spec.ts
src/shared/services/component-type.service.ts
src/title-dropdown/title-dropdown.component.html
src/title-dropdown/title-dropdown.component.ts

fix-issue-115: Disable buttons and dropdowns along with fields

---

src/primitive-list-field/primitive-list-field.component.html
src/shared/pipes/self-or-empty.pipe.spec.ts
src/shared/pipes/self-or-empty.pipe.ts

* Generates an empty primitive value if array is empty.
(Closes #137)

fix-issue-137: Fix issue with empty primitive arrays

---

package.json
src/shared/services/schema-fixer.service.spec.ts
src/shared/services/schema-fixer.service.ts

* Fixes #124 
@jmartinm Apparently I forgot to create this.

add support for allOf

---

example/app/app.config.ts
src/add-new-element-button/add-new-element-button.component.scss
src/complex-list-field/complex-list-field.component.html
src/find-replace/find-replace.component.html
src/find-replace/find-replace.component.scss
src/find-replace/find-replace.component.ts
src/find-replace/index.ts
src/json-editor.component.html
src/json-editor.component.scss
src/json-editor.module.ts
src/modal-view/index.ts
src/modal-view/modal-view.component.html
src/modal-view/modal-view.component.ts
src/object-field/object-field.component.html
src/shared/services/find-replace-all.service.spec.ts
src/shared/services/find-replace-all.service.ts
src/shared/services/index.ts
src/shared/services/modal.service.ts
src/title-dropdown/title-dropdown.component.scss
src/typings.d.ts

* Adds find-replace-all service
* Adds find replace for top level fields
* Adds modal-view component and service

implement find-replace to resolve #103

---

README.md
example/app/app.config.ts
example/typings.d.ts
src/any-type-field/any-type-field.component.html
src/any-type-field/any-type-field.component.ts
src/json-editor.component.html
src/json-editor.component.scss
src/shared/pipes/filter-and-sort-by-schema.pipe.spec.ts
src/shared/pipes/filter-and-sort-by-schema.pipe.ts
src/shared/services/app-globals.service.ts
src/typings.d.ts

* Fixes #40 
UI to be discussed.

add admin mode

---

README.md

issue-155: Add build badge and link to demo example

---

src/editor-previewer/editor-previewer.component.html
src/editor-previewer/editor-previewer.component.scss
src/editor-previewer/editor-previewer.component.ts

issue-112: Open html previews in new window

---

src/index.ts
src/modal-view/modal-view.component.html
src/modal-view/modal-view.component.ts
src/shared/interfaces/modal-options.ts

* Explicitly calls markForCheck so that template gets updated after
updating options.
* Adds new onShow callback that allows to run code after the modal is shown
in the UI.

modal view better detection change

---

README.md
src/index.ts
src/json-editor.module.ts

* Fixes exports to export everything in the app separately.
* Updates README to fix usage import and for some other outdated stuff.

fix exports for AoT and update README

---

e2e/preview-panel/preview-panel.e2e-spec.ts
src/editor-previewer/editor-previewer.component.html
src/editor-previewer/editor-previewer.component.scss
src/editor-previewer/editor-previewer.component.ts
src/json-editor.component.html
src/json-editor.component.scss
src/json-editor.component.ts

Expand editor when preview is hidden

---

example/app/app.config.ts
src/shared/interfaces/schema-option.ts
src/shared/pipes/add-always-show-fields.pipe.ts
src/shared/services/schema-fixer.service.spec.ts
src/shared/services/schema-fixer.service.ts

order and alwaysShow as arrays in config

---

e2e/app.po.ts
e2e/shortcut-action/shortcut-action.e2e-spec.ts
e2e/shortcut-action/shortcut-action.po.ts
ng2-json-editor.d.ts
ng2-json-editor.js
src/abstract-list-field/abstract-list-field.component.ts
src/primitive-field/primitive-field.component.ts
src/shared/services/dom-util.service.ts
src/shared/services/shortcut-action.service.ts
src/shared/services/tab-index.service.ts

fix-issue-164: Fix for shortcut 'move up/down'

---

src/json-editor.component.scss
src/primitive-field/primitive-field.component.html
src/searchable-dropdown/searchable-dropdown.component.html
src/searchable-dropdown/searchable-dropdown.component.scss
src/searchable-dropdown/searchable-dropdown.component.spec.ts
src/searchable-dropdown/searchable-dropdown.component.ts

* Adds a caret to dropdown.
* Removes box-shadow style.
* Fixes #178

fix enum dropdown bugs

---

src/autocomplete-input/autocomplete-input.component.html
src/json-editor.component.scss

fix typeahead position and size

---

src/primitive-field/primitive-field.component.ts
src/shared/services/schema-fixer.service.spec.ts
src/shared/services/schema-fixer.service.ts

fix-issue-197: Make disabled fields untabable

---

example/app/app.config.ts

Since there is no previewer after tabs by default if it's not set. All other PRs was failing. So this config change will fix. After this I will rebase my other prs.

fix e2e test for previewer on travis

---

src/json-editor.component.html

fix bug when no previews and tab config

---

src/complex-list-field/complex-list-field.component.html
src/object-field/object-field.component.ts

* Fixes #213 .
* Improves pagitanor performance that is in long list navigator.
However the improvement is not really obvious because the fix needed
for #213 .

fix #213 and improve paginator performance

---

src/add-field-dropdown/add-field-dropdown.component.html
src/add-field-dropdown/add-field-dropdown.component.scss

fix #221 (dropdown position for empty table-list)

---

src/searchable-dropdown/searchable-dropdown.component.scss

fix #219 (enum dropdown caret)

---

example/app/app.config.ts
example/assets/mock-data/record.json
package.json
src/json-editor.module.ts
src/shared/interfaces/schema-option.ts
src/shared/pipes/add-always-show-fields.pipe.ts
src/shared/pipes/add-always-show-toggles.pipe.ts
src/shared/pipes/index.ts
src/sub-record/sub-record.component.html
src/sub-record/sub-record.component.scss
src/sub-record/sub-record.component.ts

support toggle on top

---

src/searchable-dropdown/searchable-dropdown.component.html
src/sub-record/sub-record.component.html

* Prevents title-dropdown from closing when find-replace is used.
* Fixes searchable-dropdown issues.

fix dropdown bugs

---

src/add-field-dropdown/add-field-dropdown.component.ts

clear filter when a field is selected to be added.

---

src/modal-view/modal-view.component.html

* Fixes #246
@StellaCh, please confirm the screenshot, if that's how it should be

make confirm button for modal, green

---

src/find-replace/find-replace.component.html
src/find-replace/find-replace.component.scss
src/find-replace/find-replace.component.ts
src/shared/services/find-replace-all.service.ts

* Fixes #247
* Cleans up parameters if find-replace actions is done (modal confirm)

improve find-replace UX

---

src/any-type-field/any-type-field.component.html
src/json-editor.component.scss
src/primitive-field/primitive-field.component.html
src/primitive-field/primitive-field.component.scss
src/primitive-field/primitive-field.component.ts

* Fixes #241
* Fixes #232
* Changes how disabled is handled, now only few things are disabled,
most importantly all primitive values. Further will be resolved after
discussing in #254.

fix disabled field bugs

---

src/shared/services/window-href.service.ts
src/tree-menu/tree-menu.component.html
src/tree-menu/tree-menu.component.scss
src/tree-menu/tree-menu.component.ts

remove search from tree-menu

---

example/app/app.config.ts
src/json-editor.component.ts
src/shared/interfaces/json-editor-config.ts
src/shared/services/app-globals.service.ts
src/tree-menu/tree-menu-item.component.html
src/tree-menu/tree-menu-item.component.ts
src/tree-menu/tree-menu.component.html
src/tree-menu/tree-menu.component.spec.ts

* Adds config to set maximum depth for tree-menu on the left,
referencing #245

add menuMaxDepth config

---

example/app/app.config.ts
src/abstract-list-field/abstract-list-field.component.ts
src/add-field-dropdown/add-field-dropdown.component.html
src/add-field-dropdown/add-field-dropdown.component.scss
src/complex-list-field/complex-list-field.component.html
src/json-editor.component.scss
src/list-action-group/list-action-group.component.html
src/list-action-group/list-action-group.component.ts
src/object-field/object-field.component.html
src/primitive-list-field/primitive-list-field.component.html
src/shared/interfaces/schema-option.ts
src/table-list-field/table-list-field.component.html

* Fixes #169
* Cleans up add-field-dropdown template
* Replaces UNICODE chars/icons with font-awesome
* Unifies size of icon buttons

add sortable config for lists

---

src/json-editor.component.scss
src/primitive-field/primitive-field.component.html
src/primitive-field/primitive-field.component.spec.ts
src/primitive-field/primitive-field.component.ts
src/searchable-dropdown/searchable-dropdown.component.html
src/searchable-dropdown/searchable-dropdown.component.ts
src/shared/services/dom-util.service.ts
src/shared/services/shortcut-action.service.ts
src/tree-menu/tree-menu-item.component.ts

highlights field instead of flashing

---

src/sub-record/sub-record.component.html

scrolls to top when a toggle is clicked on the menu

---

src/abstract-field/abstract-field.component.ts
src/abstract-list-field/abstract-list-field.component.ts
src/complex-list-field/complex-list-field.component.html
src/object-field/object-field.component.html
src/object-field/object-field.component.ts
src/primitive-list-field/primitive-list-field.component.html
src/sub-record/sub-record.component.html
src/sub-record/sub-record.component.ts
src/table-item-field/table-item-field.component.html
src/table-item-field/table-item-field.component.ts
src/table-list-field/table-list-field.component.html

* Refactors pathCache and moves getting path for child logic to
abstract-field.component so that every component shares.
* Fixes #271

refactor pathCache and fix #271

---

src/find-replace/find-replace.component.html
src/find-replace/find-replace.component.ts
src/json-editor.module.ts
src/modal-view/modal-view.component.ts
src/sub-record/sub-record.component.ts
src/tree-menu/tree-menu-item.component.ts

* Fixes aot build errors that appear on applications which uses the
ng2-json-editor and ngc.
* Also fixes #274

fix aot build errrors

---

src/complex-list-field/complex-list-field.component.ts
src/primitive-field/primitive-field.component.ts

organize super.ngOnInit() calls

---

e2e/shortcut-action/shortcut-action.e2e-spec.ts
src/complex-list-field/complex-list-field.component.ts
src/shared/interfaces/custom-shortcuts.ts
src/shared/services/shortcut-action.service.ts
src/shared/services/shortcut.service.ts

fix-issue-289: Add shortcut for adding below item

---

src/json-editor.component.scss
src/primitive-field/primitive-field.component.scss
src/table-item-field/table-item-field.component.scss

* Improves contrast in between fields and minor fixes.

table css styling

---

example/app/app.config.ts
src/ref-field/ref-field.component.html
src/ref-field/ref-field.component.ts
src/shared/interfaces/index.ts
src/shared/interfaces/ref-anchor-attributes.ts
src/shared/interfaces/ref-config.ts

* Fixes #293
* Adds example config (could remove if wanted @jmartinm)
* Small bug fixes for ref-field

add linkTextBuilder for ref-field

---

example/app/app.config.ts
src/any-type-field/any-type-field.component.ts
src/json-editor.component.ts
src/object-field/object-field.component.html
src/object-field/object-field.component.ts
src/primitive-field/primitive-field.component.ts
src/shared/services/app-globals.service.ts
src/shared/services/keys-store.service.spec.ts
src/shared/services/keys-store.service.ts
src/sub-record/sub-record.component.html
src/sub-record/sub-record.component.ts

* Fixes automatic change detection on disabled fields
* Fixes enabling hidden fields on admin mode
(Closes #243)
Signed-off-by: harunurhan <harunurhan17@gmail.com>

issue-243: Fixes admin bug to reflect changes automatically

---

src/primitive-field/primitive-field.component.html
src/primitive-field/primitive-field.component.scss
src/primitive-field/primitive-field.component.ts
src/shared/services/katex.service.ts
src/string-input/string-input.component.html
src/string-input/string-input.component.ts

Fix string input issues

---

src/abstract-list-field/abstract-list-field.component.ts
src/shared/pipes/self-or-empty.pipe.spec.ts
src/shared/pipes/self-or-empty.pipe.ts

fix deleting list element bugs

---

src/searchable-dropdown/searchable-dropdown.component.html
src/searchable-dropdown/searchable-dropdown.component.ts

fix searchable-dropdown autoclose bug

---

src/shared/pipes/filter-hidden-fields.pipe.spec.ts
src/shared/pipes/filter-hidden-fields.pipe.ts
src/tree-menu/tree-menu-item.component.html
src/tree-menu/tree-menu-item.component.ts
src/tree-menu/tree-menu.component.html
src/tree-menu/tree-menu.component.ts

update tree-menu when admin mode is enabled

---

src/abstract-field/abstract-field.component.ts
src/primitive-field/primitive-field.component.html
src/primitive-field/primitive-field.component.ts

* Fixes tabbing outside a field by marking it for check.

fix-issue-315: Fixes error panel update on field deletion

---

src/index.ts
src/shared/classes/index.ts
src/shared/classes/sized-stack.spec.ts
src/shared/classes/sized-stack.ts
src/shared/interfaces/custom-shortcuts.ts
src/shared/interfaces/index.ts
src/shared/interfaces/json-patch.ts
src/shared/services/json-store.service.spec.ts
src/shared/services/json-store.service.ts
src/shared/services/keys-store.service.ts
src/shared/services/shortcut-action.service.ts
src/shared/services/shortcut.service.spec.ts
src/shared/services/shortcut.service.ts

* Adds initial json-patch support.
* Changes history from snapshot of whole json to reverse json-patch.
* Populates history when something is removed.

add initial json-patch support

---

src/html-view/html-view.component.html
src/html-view/html-view.component.scss

* This reduces security risk due to `Mixed content` in #322

use object instead of iframe

---

src/shared/services/schema-validation.service.ts

validation: Set custom date format validation

---

example/app/app.config.ts
src/shared/interfaces/custom-format-validation.ts
src/shared/interfaces/index.ts
src/shared/interfaces/json-editor-config.ts
src/shared/services/schema-validation.service.ts

schema-format: Make schema format validation configurable

---

src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.scss

* Fixes #334
* Moves html from table to flex-box

refactor navigator html and make it sticky

---

src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.ts
src/shared/interfaces/long-list-navigator-config.ts

* Adds template support for complex-list navigator to add extra item to
the navigator header.

add template support for complex-list navigator

---

package.json

remove ts-helper peerDepedency

---

src/shared/services/empty-value.service.ts
src/shared/services/keys-store.service.ts

* Cleans everything if key is deleted including all keys thast belongs
its childred.
* Fixes #347

complete cleanup of keys and fix #347

---

e2e/shortcut-action/shortcut-action.e2e-spec.ts
example/assets/mock-data/record.json
src/shared/interfaces/custom-shortcuts.ts
src/shared/services/shortcut-action.service.ts
src/shared/services/shortcut.service.ts

add shortcuts to move in the most outer list.

---

src/primitive-field/primitive-field.component.scss

wrap content on primitive field with patch

---

src/add-field-dropdown/add-field-dropdown.component.html
src/add-field-dropdown/add-field-dropdown.component.ts
src/add-field-dropdown/add-nested-field-dropdown.component.html
src/add-field-dropdown/add-nested-field-dropdown.component.ts
src/complex-list-field/complex-list-field.component.html
src/json-editor.component.scss
src/list-action-group/list-action-group.component.html
src/list-action-group/list-action-group.component.ts
src/object-field/object-field.component.html
src/primitive-field/primitive-field.component.scss
src/primitive-list-field/primitive-list-field.component.html
src/table-list-field/table-list-field.component.html

finish disabled field implementation

---

src/shared/services/json-store.service.ts

* Fixes #358
* Fixes undo crash while trying to remove undo patch fron global
json-patches which are associated to components.

support undo for setting new value to top level

---

src/shared/services/json-store.service.ts

rebuild keys if necessary during setIn

---

src/complex-list-field/complex-list-field.component.html
src/complex-list-field/complex-list-field.component.scss
src/complex-list-field/complex-list-field.component.ts

@jmartinm requires a patch release after

hide All-Edit switch if viewTemplateConfig absent

---

src/bottom-console/errors-console-tab/errors-console-tab.component.ts
src/bottom-console/patches-console-tab/patches-console-tab.component.ts

* Sets initial valuse for patches and error counts

fix bottom-console badges

---

src/shared/services/shortcut-action.service.ts

* Fixes undo problem but only works when an array item is deleted not
when a property is deleted.

fix undo crash

---

src/abstract-field/abstract-field.component.ts
src/add-field-dropdown/add-nested-field-dropdown.component.ts
src/complex-list-field/complex-list-field.component.ts
src/primitive-field/primitive-field.component.ts

* Adds ubscribe for onKeysChange on add-nested-field-dropdown.
* Populates subcriptions to an array on field components,
then later unsubscribes all array in ngOnDestroy hook.

improve subscription.unsubscribe handling

---

src/primitive-field/primitive-field.component.html
src/primitive-field/primitive-field.component.scss

* Adds colored left border and icon (fixes #387)

improve primitive-field view

---

src/json-editor.component.html
src/json-editor.component.scss
src/json-editor.component.ts
src/shared/interfaces/json-editor-config.ts

add compact mode

---

README.md
example/app/app.component.html
src/bottom-console/patches-console-tab/patches-console-tab.component.ts
src/json-editor.component.ts
src/shared/services/json-store.service.spec.ts
src/shared/services/json-store.service.ts
src/shared/services/keys-store.service.spec.ts
src/shared/services/keys-store.service.ts

* Adds jsonPatchesChange output to json-editor.component so that it
notifies when a patch accepted or rejected.
* Updates @Input @Output docs on README

add jsonPatchesChange and update docs

---

src/json-editor.component.scss

Make dropdowns (add-field, autocomplete, searchable etc.) better, in case of a lot of items.

set max-height with scroll on y for all dropdowns

---

src/shared/services/schema-fixer.service.ts

warn for config & schema mismatch

---

src/shared/directives/shortcuts.directive.ts

refactor shortcuts directive

---

src/shared/interfaces/schema-option.ts
src/shared/services/schema-fixer.service.spec.ts
src/shared/services/schema-fixer.service.ts

add alwaysShowRegExp config

---

src/json-editor.component.html
src/json-editor.component.ts
src/shared/services/json-store.service.ts
src/shared/services/schema-fixer.service.ts

* stores schema and fixedSchema seperately so that each time only
config is changed, it is used to enhanced original schema.

fix crash when config is changed on runtime and consistent undo

---

example/app/app.config.ts
package.json
src/shared/interfaces/custom-error-messages.ts
src/shared/interfaces/index.ts
src/shared/interfaces/schema-option.ts
src/shared/services/schema-validation.service.ts

support custom schema validation error messages

---

src/editor-previewer/editor-previewer.component.scss
src/primitive-field/primitive-field.component.scss

TODO: squash all into 1 commit

small style fixes

---

src/bottom-console/patches-console-tab/patches-console-tab.component.html
src/bottom-console/patches-console-tab/patches-console-tab.component.scss
src/bottom-console/patches-console-tab/patches-console-tab.component.ts

add patch actions to patches console tab

---

src/json-editor.component.html
src/json-editor.component.scss

remove left-border on compact mode

---

src/add-new-element-button/add-new-element-button.component.scss
src/json-editor.component.scss
src/object-field/object-field.component.html
src/object-field/object-field.component.ts
src/shared/interfaces/schema-option.ts
src/sub-record/sub-record.component.html
src/sub-record/sub-record.component.ts

add custom title dropdown item support

---

example/assets/mock-data/record.json
src/primitive-list-field/primitive-list-field.component.html
src/shared/services/component-type.service.spec.ts
src/shared/services/component-type.service.ts

display array ref-fields as primitive-list

---

example/assets/mock-data/patches.json
src/primitive-field/primitive-field.component.html

fix patch popover bug when patch.value is a number

---

src/bottom-console/patches-console-tab/patches-console-tab.component.html

hide accept/reject all if there is no patch

---

src/json-editor.component.scss

remove html, body style

---

e2e/preview-panel/preview-panel.e2e-spec.ts
src/bottom-console-badges/bottom-console-badges.component.scss
src/json-editor.component.html
src/json-editor.component.scss

Screnshots:
1. Maximized Preview
2. Minimized Preview
Signed-off-by: Dinika Saxena <dinika.saxena@cern.ch>

add icon in sidebar to toggle preview

---

src/bottom-console-badges/bottom-console-badges.component.scss
src/json-editor.component.scss

Signed-off-by: Dinika Saxena <dinika.saxena@cern.ch>

fix size of containers and icons

---

src/autocomplete-input/autocomplete-input.component.html
src/autocomplete-input/autocomplete-input.component.ts
src/primitive-field/primitive-field.component.html
src/primitive-field/primitive-field.component.ts
src/shared/interfaces/autocompletion-config.ts

* Refactoring includes taking app state related services out of
autcomplete-input so that it stays simple and "dumb"

fix autocomplete selection bug and refactor

---

example/configs/config.ts
package.json
src/add-or-replace-patch/add-or-replace-patch.component.html
src/primitive-field/primitive-field.component.spec.ts
src/shared/pipes/index.ts
src/shared/pipes/sort-keys-by-schema.pipe.ts
src/shared/services/compare-keys-by-schema.service.spec.ts
src/shared/services/compare-keys-by-schema.service.ts
src/shared/services/index.ts
src/shared/services/keys-store.service.spec.ts
src/shared/services/keys-store.service.ts

sort fields in patches according to config

---

.vscode/launch.json
src/json-editor.component.ts
src/shared/interfaces/json-editor-config.ts

* `isPreviewerHidden` now gets a default value `false` from the config file.

Previewer option from config

---

src/shared/services/json-store.service.ts

* Now a key can be added, deleted then added back.

fix add-field dropdowns readding issue

---

src/complex-list-field/complex-list-field.component.ts

fix item addition for complex-list

---

src/bottom-console/abstract-console-tab/abstract-console-tab.component.scss
src/bottom-console/patches-console-tab/patches-console-tab.component.html
src/bottom-console/patches-console-tab/patches-console-tab.component.ts
src/json-editor.module.ts

ref: inspirehep/record-editor#377

group patches in conflict tab by field

---

example/app/app.component.html
src/bottom-console/patches-console-tab/patches-console-tab.component.html
src/bottom-console/patches-console-tab/patches-console-tab.component.scss
src/bottom-console/patches-console-tab/patches-console-tab.component.ts
src/shared/services/app-globals.service.ts

It is rendered in the "Conflicts" sections of bottom console,
before batch action buttons.

add patchesHeaderTemplate config

---

src/table-list-field/table-list-field.component.html
src/table-list-field/table-list-field.component.scss

Ref: inspirehep/inspirehep#1111

add vertical space btw add-patches for table-list

---

src/json-editor.component.scss

ref: inspirehep/inspirehep#1226

Make navigation tab sticky

---

src/bottom-console/patches-console-tab/patches-console-tab.component.html

Ref: inspirehep/inspirehep#1388

sort patches (conflicts) alphabetically

---

src/complex-list-field/complex-list-field.component.scss

ui: fix sticky tabs

---

src/complex-list-field/complex-list-field.component.scss

Fix Sticky Tabs

---

.gitignore
src/ref-field/ref-field.component.html
src/ref-field/ref-field.component.ts
src/shared/interfaces/ref-config.ts

* Ref inspirehep/inspirehep#1255

ref: addition of string-input

---

src/json-editor.component.scss

ui: autocomplete field expanded for positions.institution

---

src/primitive-field/primitive-field.component.ts

ref:inspirehep/inspirehep#2269

validate also after value change

---

src/shared/services/json-store.service.ts

* ref: https://github.com/cern-sis/issues-inspire/issues/378

fixed updating json data

---

package.json

Reverts inveniosoftware-contrib/ng2-json-editor#549

Revert "v0.25.52"

---

src/shared/services/json-store.service.ts

Reverts inveniosoftware-contrib/ng2-json-editor#548

Revert "fixed updating json data"

---

src/shared/services/compare-keys-by-schema.service.ts

* ref: cern-sis/issues-inspire#424

fix undefined property error
