README.md, src/shared/services/schema-fixer.service.spec.ts, src/shared/services/schema-fixer.service.ts
* Adds anyOf support where all anyOf items have same properties
and are objects. Picks the first one, merges all enum values and
removes patter and format rules.
* Adds tests for schema-fixer service
Shall we add the info about limitation of this support (like in the commit message) to somewhere
in README?
@jmartinm
=> add limited support for anyOf

README.md, src/any-type-field/any-type-field.component.html, src/json-editor.module.ts, src/ref-field/index.ts, src/ref-field/ref-field.component.html, src/ref-field/ref-field.component.scss, src/ref-field/ref-field.component.ts, src/shared/services/component-type.service.spec.ts, src/shared/services/component-type.service.ts, src/shared/services/dynamic-template-loader.service.ts, src/shared/services/index.ts
* Adds dynamic-templater-loader service that can compile and load angular2 templates
into DOM in runtime by wrapping them with a dummy component and a
module.(referencing #45)
* Adds ref-field component that handles the object field with $ref
inside using the template in x_editor_ref_config from schema.
=> implement customizable $ref field

README.md, package.json, src/editor-previewer/editor-previewer.component.html, src/json-editor.module.ts
* Removes pdf.js and pdf type for pdf previews in favor of iframe
since all major browsers' pdf viewers are better and faster at
rendering the pdf. (Fixes #50, Fixes #59)
=> remove pdf.js in favor of iframe

src/primitive-list-field/primitive-list-field.component.html, src/shared/services/json-store.service.spec.ts, src/shared/services/json-store.service.ts
* Fixes the bug that occurs  when a new field with `"type": "array"' is
added. The bug is caused by `immutablejs` that inserts always Map in `setIn`
if a key doesn't exist in given keyPath.
* Fixes the bug with primitive-list, it displays values correctly.
=> fix list related bugs

README.md, example/app/app.config.ts, src/add-new-element-button/add-new-element-button.component.ts, src/autocomplete-input/autocomplete-input.component.html, src/autocomplete-input/autocomplete-input.component.ts, src/complex-list-field/complex-list-field.component.html, src/complex-list-field/complex-list-field.component.scss, src/complex-list-field/complex-list-field.component.ts, src/editor-previewer/index.ts, src/json-editor.component.scss, src/json-editor.component.ts, src/primitive-field/primitive-field.component.html, src/primitive-field/primitive-field.component.spec.ts, src/primitive-field/primitive-field.component.ts, src/typings.d.ts
* Changes the primitive field to apply the changes to
global store on enter pressed and on input blur.
* Updates tests of primitive-field for blur/press-enter
store update.
* Adds x_editor_long_list_navigator config option.
* Adds navigator when long_list navigator is enabled for
a complext list. Navigator has find functionality and a paginator.
* Removes tsc error for Preview.
TODOS:
* Remove changes in example/*
* Clean the complex list code if possible, might need to  move
some code to a service.
=> Implement long list navigator.

README.md, example/app/app.config.ts, src/primitive-field/primitive-field.component.html, src/primitive-field/primitive-field.component.scss, src/primitive-field/primitive-field.component.ts, src/typings.d.ts
* Adds x_editor_link_builder function that takes a primitive value
and returns a url string which will be pointed by a small anchor element
next to the input element of primitive field. (Fixes #80)
* Adds example config for x_editor_link_builder.
=> add configurable link button to primitive-field

src/add-field-dropdown/add-field-dropdown.component.spec.ts, src/add-field-dropdown/add-field-dropdown.component.ts, src/complex-list-field/complex-list-field.component.html, src/complex-list-field/complex-list-field.component.ts, src/json-editor.component.ts, src/object-field/object-field.component.ts, src/shared/pipes/add-always-show-fields.pipe.ts, src/shared/pipes/different-keys.pipe.spec.ts, src/shared/pipes/different-keys.pipe.ts, src/shared/pipes/filter-and-sort-by-schema.pipe.spec.ts, src/shared/pipes/filter-and-sort-by-schema.pipe.ts, src/shared/pipes/filter-by-expression.pipe.ts, src/shared/pipes/sanitize-url.pipe.ts, src/shared/pipes/self-or-empty.pipe.ts, src/shared/pipes/underscore-to-space.pipe.ts, src/table-list-field/table-list-field.component.ts, src/tree-menu/tree-menu-item.component.ts, src/tree-menu/tree-menu.component.ts
* Fixes #89
* Purifies pipes that take primitive arguments.
* Changes pipe arguments from Array to Immutable.Set
and purify those pipes.
* Changes `keys` type in components from Array to Immutable.Set
so that it can be passed to pipes.
=> purify pipes and use immutables in pipes

src/primitive-field/primitive-field.component.html
* Adds the link button to editable fields with format:'url' in their schema.
(Closes #152)
=> issue-152: Add link button to editable links

README.md, angular-cli.json, example/app/app.component.scss, package.json, src/complex-list-field/complex-list-field.component.html, src/complex-list-field/complex-list-field.component.scss, src/editor-previewer/editor-previewer.component.html, src/modal-view/modal-view.component.html, src/primitive-field/primitive-field.component.html, src/primitive-list-field/primitive-list-field.component.html, src/table-list-field/table-list-field.component.html
* Adds font-awesome to example and replaces unicode icons with it.
* Documents styling dependencies.
=> add font-awesome and replace unicode icons

src/abstract-list-field/abstract-list-field.component.ts, src/json-editor.component.ts, src/object-field/object-field.component.ts, src/primitive-list-field/primitive-list-field.component.ts, src/shared/interfaces/index.ts, src/shared/interfaces/path-cache.ts
* Every time that path array was needed a new object was obtained.
So, angular was re-rendering every time all the components and
the UI was getting slow when typing. Caching the paths fixed the
re-rendering process only when a new path was added.
(Closes #179)
=> fix-issue-179: Fix slow performance issue

src/abstract-tracker/abstract-tracker.component.ts, src/complex-list-field/complex-list-field.component.html, src/editor-previewer/editor-previewer.component.html, src/json-editor.component.html, src/object-field/object-field.component.html, src/primitive-list-field/primitive-list-field.component.html, src/table-list-field/table-list-field.component.html, src/tree-menu/tree-menu-item.component.html, src/tree-menu/tree-menu.component.html
* Replaces trackByFunction in table-list component with
a trackByIndex function. As a result when we update a
specific value in a table's element, only the specifc
element is re-rendered.
(Closes #199)
=> fix-issue-199: Fix tab after editing a field.

src/abstract-list-field/abstract-list-field.component.ts, src/complex-list-field/complex-list-field.component.html, src/complex-list-field/complex-list-field.component.scss, src/complex-list-field/complex-list-field.component.ts, src/json-editor.component.scss, src/json-editor.module.ts, src/list-action-group/index.ts, src/list-action-group/list-action-group.component.html, src/list-action-group/list-action-group.component.ts, src/object-field/object-field.component.html, src/object-field/object-field.component.scss, src/primitive-list-field/primitive-list-field.component.html, src/table-item-field/index.ts, src/table-item-field/table-item-field.component.html, src/table-item-field/table-item-field.component.scss, src/table-item-field/table-item-field.component.ts, src/table-list-field/table-list-field.component.html, src/table-list-field/table-list-field.component.scss
* Changes the case when a component manages two level in a path
(has two nested ngFor over the value) by re using object-field for
complex-list elements and new table-item-field for table-list elements.
* Adds list-action-group component to share template of up/down and
delete.
* Fix style which is broken because of html structure change.
=> refactor component templates

README.md
Today @zzacharo and I realized that this is needed 😄
=> add npm link documentation

src/add-field-dropdown/add-field-dropdown.component.scss, src/json-editor.component.scss
It was bothering me before the alignment of the buttons and dropdowns were popping out from a different a place.
=> fix add-field-dropdown style

src/json-editor.component.scss
=> add padding to top-level add-field-dropdown

src/primitive-field/primitive-field.component.html, src/primitive-field/primitive-field.component.spec.ts, src/primitive-field/primitive-field.component.ts
* Uses schema.componentType in primitive field to avoid using
getComponentType unnecessarily.
=> use schema.componentType in primitive field

src/abstract-list-field/abstract-list-field.component.ts, src/object-field/object-field.component.ts, src/primitive-field/primitive-field.component.ts, src/shared/services/json-store.service.spec.ts, src/shared/services/json-store.service.ts
* Replaces setIn with removeIn in some places.
* Fixes #235
* Removes a primitive field from an object or primitive list if value
is empty string or undefined. This reduces number of accidental empty
strings in the record and allows users to delete property of items of
table list.
@jmartinm @zzacharo please play with it locally.
=> skip validation and remove field if string is empty

src/autocomplete-input/autocomplete-input.component.spec.ts, src/primitive-field/primitive-field.component.spec.ts, src/shared/services/keys-store.service.spec.ts, src/shared/services/keys-store.service.ts
* Refactors keys-store addKey method by making schema param optional so
that it can be used by parent apps (in config's callback functions)
easily.
=> refactor keys-store

src/shared/services/keys-store.service.spec.ts, src/shared/services/keys-store.service.ts
* Reverts previous refactoring because it turned out that addKey wasn't
the function that needs to be refactored
* Do same refactoring buildKeysMapRecursivelyForPath method
( param type change will be gone when #330 is fixed )
=> revert previous and refactor buildKeysMapForPath

src/primitive-field/primitive-field.component.ts
* Adds timeout to onValueChange callback function call to workaround
the case the value is changed back to previous value inside the
callback.
=> add timeout to onValueChange callback

src/shared/services/json-store.service.spec.ts, src/shared/services/json-store.service.ts
* Now a javascript object or array can be passed to addIn and setIn
functions, and they are later converted to Immutable. Thanks to this
parent app doesn't need to care about complexity of immutable data
structures.
=> add non immutable support to json-store.service

package.json, src/add-field-dropdown/add-field-dropdown.component.spec.ts, src/autocomplete-input/autocomplete-input.component.spec.ts, src/json-editor.component.scss, src/json-editor.module.ts, src/modal-view/modal-view.component.ts, src/primitive-field/primitive-field.component.spec.ts, src/searchable-dropdown/searchable-dropdown.component.spec.ts, src/title-dropdown/title-dropdown.component.scss
* Changes ng2-bootstrap to ngx-bootstrap.
* Upgrades the version of the package to -beta.1
becuase latest (-beta.3) is breaking popovers.
* Adds missing types for diff library
* Fixes #275
=> updage to ngx-boostrap and fix #275

src/abstract-list-field/abstract-list-field.component.ts, src/shared/services/json-store.service.ts, src/shared/services/keys-store.service.spec.ts, src/shared/services/keys-store.service.ts, src/shared/services/shortcut-action.service.ts
* Fixes #354
* Adds moveIn utility to json-store so that moving will be shared btw
components and shortcuts.
* Adds test for deleteKey.
* Removes types from method comments.
=> swap keys while moving complex list items

src/shared/services/remote-autocompletion.service.ts
`typedoc` compiles the code when building the docs, and uses `tsc` not `ngc` that's why missing import was causing docs build to fail for docs but not library build.
=> fix docs building issue (closes #357)

src/complex-list-field/complex-list-field.component.html, src/complex-list-field/complex-list-field.component.scss, src/complex-list-field/complex-list-field.component.ts, src/json-editor.component.scss, src/shared/interfaces/paginated-item.ts, src/shared/interfaces/view-template-config.ts
* Adds switch to see only complex-list items to edit.
* Changes .active class color for complex-list navigator.
=> add switch to see only items with edit form

src/primitive-field/primitive-field.component.html, src/primitive-field/primitive-field.component.spec.ts, src/primitive-field/primitive-field.component.ts, src/shared/interfaces/json-schema.ts, src/shared/services/empty-value.service.spec.ts, src/shared/services/empty-value.service.ts
* EmptyValueService returns schema.default if it is set (fixes #412)
* PrimitiveField commits if the current value is default one
* EmptyValueService respects alwaysShow
=> use schema.default for empty value

src/shared/services/json-store.service.ts
* Fixes the bug when setJson called the second time with a different
value but subscribe is returning a previous value due to
ReplaySubject(1).
* Adds license header
=> change json$ to be Subject instead of ReplaySubject

example/assets/mock-data/patches.json, src/abstract-field/abstract-field.component.ts, src/abstract-list-field/abstract-list-field.component.ts, src/object-field/object-field.component.html, src/primitive-field/primitive-field.component.html, src/primitive-field/primitive-field.component.ts, src/shared/interfaces/index.ts, src/shared/interfaces/json-patches-by-op.ts, src/shared/pipes/last-path-element.pipe.ts, src/shared/services/json-store.service.ts
* Also refactors patch handling in general by using only grouped json
patches on components.
* Improve lastPathElement pipe by using only string operations instead
of creating an array with split.
This unifies add/remove patch look UI as well, only thing that is known and not fixed is https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/453
=> fix add/remove patches for object properties

src/add-field-dropdown/add-field-dropdown.component.html, src/add-field-dropdown/add-field-dropdown.component.scss, src/bottom-console-badges/bottom-console-badges.component.html, src/bottom-console-badges/bottom-console-badges.component.scss, src/json-editor.component.html, src/json-editor.component.scss, src/json-editor.component.ts, src/object-field/object-field.component.html, src/table-list-field/table-list-field.component.html, src/tree-menu/tree-menu.component.scss
The sidebar collapses to a narrower bar, like so:
On a smaller screen (iPad):
When the sidebar is expanded:
=> make the sidebar collapsible

e2e/shortcut-action/shortcut-action.e2e-spec.ts, e2e/shortcut-action/shortcut-action.po.ts, src/primitive-field/primitive-field.component.scss, src/primitive-field/primitive-field.component.spec.ts, src/shared/services/dom-util.service.ts, src/string-input/string-input.component.html, src/string-input/string-input.component.ts
* This fixes the issue with Firefox which inserts unnecesary <br>'s to
div[contenteditable]. Those <br>'s become the part of the actual value
in the edited json and creates problems with validation etc.
=> change contenteditable el from div to span

src/autocomplete-input/autocomplete-input.component.html, src/autocomplete-input/autocomplete-input.component.ts, src/json-editor.component.scss
For some reason underlying ngx-bootstrap's typeahead wasn't working
consistently for selecting a completion by mouse click.
This is simplest and fastest solution without touching the
ngx-bootstrap's code.
NOTE: upgrading ngx-bootstrap wasn't an option since we
have to run angular 4 and and ngx-bootstrap 2.
=> fix auto-complete field selection by clicking bug
